name: Docker Cleanup

on:
  schedule:
    - cron: '00 0 * * *'
  workflow_dispatch:

jobs:
  delete-old-images-main:
    name: Delete Untagged Images
    runs-on: ubuntu-latest
    permissions:
        packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          dry-run: true
          delete-ghost-images: true
          delete-partial-images: true
          delete-orphaned-images: true
          validate: true
          token: '${{ github.token }}'
          owner: 'sysadminsmedia'
          repository: 'homebox'
          package: 'homebox,devcache'
          use-regex: true
          exclude-tags: latest,main,*.*.*,0.*,0
          older-than: 180 days
