name: Docker Cleanup

on:
  schedule:
    - cron: '00 0 * * *'
  workflow_dispatch:

jobs:
  delete-old-images-main:
    name: Delete Untagged Images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: snok/container-retention-policy@v2.2.1
        with:
          # The type of account. Can be either 'org' or 'personal'.
          account-type: org 
          # The name of the organization. Only required if the account type is 'personal'.
          org-name: sysadminsmedia # optional, default is 
          # Image name to delete. Supports passing several names as a comma-separated list.
          image-names: homebox
          # The cut-off for which to delete images older than. For example '2 days ago UTC'. Timezone is required.
          cut-off: 90 days ago UTC
          # Personal access token with read and delete scopes.
          token: ${{ secrets.GITHUB_CLEANUP_PAT }}
          # Restrict deletions to images without specific tags. Supports Unix-shell style wildcards
          skip-tags: latest,latest-rootless,0.*,0.*-rootless,main,main-rootless,vnext,vnext-rootless,0,0-rootless # optional
          # Do not actually delete images. Print output showing what would have been deleted.
          dry-run: true # optional, default is false
          # The token type. Can be either 'pat' or 'github-token'. If 'github-token', then image-names must the package name of repository from where this action is invoked.
          token-type: pat # optional, default is pat

  delete-old-images-devcache:
    name: Delete Cache Old Images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: snok/container-retention-policy@v2.2.1
        with:
          # The type of account. Can be either 'org' or 'personal'.
          account-type: org 
          # The name of the organization. Only required if the account type is 'personal'.
          org-name: sysadminsmedia # optional, default is 
          # Image name to delete. Supports passing several names as a comma-separated list.
          image-names: devcache
          # The cut-off for which to delete images older than. For example '2 days ago UTC'. Timezone is required.
          cut-off: 90 days ago UTC
          # Personal access token with read and delete scopes.
          token: ${{ secrets.GITHUB_CLEANUP_PAT }}
          # Do not actually delete images. Print output showing what would have been deleted.
          dry-run: true # optional, default is false
          # The token type. Can be either 'pat' or 'github-token'. If 'github-token', then image-names must the package name of repository from where this action is invoked.
          token-type: pat # optional, default is pat
